## init nacos env configmap
apiVersion: v1
kind: ConfigMap
metadata:
    name: nacos-env-config
data:
    PREFER_HOST_MODE: hostname
    MODE: standalone
    SPRING_DATASOURCE_PLATFORM: mysql
    MYSQL_SERVICE_HOST: mysql-svc
    MYSQL_SERVICE_DB_NAME: nacos_devtest
    MYSQL_SERVICE_PORT: "13306"
    MYSQL_SERVICE_USER: root
    MYSQL_SERVICE_PASSWORD: t0p8fPAck77
    MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    NACOS_AUTH_IDENTITY_KEY: "2222"
    NACOS_AUTH_IDENTITY_VALUE: 2xxx
    NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
---
## install nacos deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: nacos
    labels:
        app: nacos
spec:
    serviceName: nacos-svc
    replicas: 1
    selector:
        matchLabels:
            app: nacos
    template:
        metadata:
            labels:
                app: nacos
        spec:
            containers:
                - name: nacos
                #   image: nacos/nacos-server:latest    # for windows
                  image: erzbir/nacos-server-m1-java17:latest
                  resources:
                      limits:
                          cpu: 1
                          memory: 2Gi
                  envFrom:
                      - configMapRef:
                            name: nacos-env-config
                  livenessProbe:
                      tcpSocket:
                          port: 8848
                  ports:
                      - containerPort: 8848
                        name: nacos-8848
                      - containerPort: 9848
                        name: nacos-9848
